<?php
/**
 * Plugin Name: Super Fast Blog Ai
 * Plugin URI: https://waatechdigital.com/super-fast-ai-blog-revolutionizing-content-creation-in-wordpress/
 * Description: Super Fast Blog Ai automatic article generator by the OpenApi key used, which is seo friendly and human readable content.Featured image generated by the pixaby. 
 * Version: 1.0.0
 * Tested up to: 6.7
 * Author: waatechdigital
 * Author URI: https://waatechdigital.com
 * License: GPL2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: super-fast-blog-ai
 */

// Exit if accessed directly.


if ( ! defined( 'ABSPATH' ) ) exit;

require_once __DIR__ . '/vendor/autoload.php';


use Orange\AiBlog\Src\Class_Setting_Management;
use Orange\AiBlog\Src\Class_Aititlegenerate;
use Orange\AiBlog\Src\Class_Logschedulepost;
use Orange\AiBlog\Src\Class_Articlegenerate;


class Class_super_fast_blog_ai
    { 
        private $setting_instance;
        private $titlegenerate;
        private $logschedulepost;
        private $articlegenerate;
        
        /**
         * Plugin version
         *
         * @var string
         */
        const VERSION = '1.0.0';

        public function __construct()
        {  
            $this->otslf_define_constants();
            add_action('admin_menu', [$this, 'otslf_ai_blog_menu']);
            add_action('admin_enqueue_scripts', [$this, 'otslf_ai_blog_enqueue_assets']);
            add_action('admin_init', [$this, 'otslf_initialize_settings']);
            register_activation_hook(__FILE__, [$this, 'otslf_db_activate']);    //create the db 
            $this->titlegenerate = new Orange\AiBlog\Src\Class_Aititlegenerate();    
            $this->logschedulepost = new Class_Logschedulepost();
            $this->articlegenerate = new Class_Articlegenerate();
        }
        
        
        public function otslf_db_activate(){        

            global $wpdb;
            $table_name = $wpdb->prefix . 'slf_schedule_post_title_log';
            $generate_table = $wpdb->prefix . 'slf_generated_title';
            $charset_collate = $wpdb->get_charset_collate();

            $sql = "CREATE TABLE $table_name (
            id mediumint(9) NOT NULL AUTO_INCREMENT,
            title text NOT NULL,
            status varchar(1000) NOT NULL,
            postid int(100) NOT NULL,
            charaters int(100) NOT NULL,
            modelused varchar(100) NOT NULL,
            indicat varchar(100) NOT NULL,
            log_time datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
            PRIMARY KEY  (id)
            ) $charset_collate;";

            require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
            dbDelta($sql);
            
            $sql = "CREATE TABLE $generate_table (
            id mediumint(9) NOT NULL AUTO_INCREMENT,
            promt_title text NOT NULL,
            generate_title text NOT NULL,
            protid int(100) NOT NULL,
            ctime datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
            PRIMARY KEY  (id)
            ) $charset_collate;";

            require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
            dbDelta($sql);
        } 

        public function otslf_define_constants()
        {
            define('OTSLF_AI_BLOG_VERSION', self::VERSION);
            define('OTSLF_AI_BLOG_FILE', __FILE__);
            define('OTSLF_AI_BLOG_PATH', __DIR__);
            define('OTSLF_AI_BLOG_PLUGIN_DIR', plugin_dir_path(__FILE__));
            define('OTSLF_AI_BLOG_URL', plugins_url('', OTSLF_AI_BLOG_FILE));
            define('OTSLF_AI_BLOG_ASSETS', OTSLF_AI_BLOG_FILE . '/assets');
        }

        public function otslf_ai_blog_enqueue_assets()
        {       
            $screen = get_current_screen();

            if ( $screen->id === 'toplevel_page_sf-blog-ai' ) { 
                         
            wp_enqueue_style('google-fonts-inter', 'https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap', array(), time(), false);  
            wp_enqueue_style('setting-css', plugin_dir_url(__FILE__) . 'assets/css/setting.css', array(), time(), false);   
            wp_enqueue_style('orange-css', plugin_dir_url(__FILE__) . 'assets/css/style.css', array(), time(), false);                
            wp_enqueue_style('datatables-css',  plugin_dir_url(__FILE__) . 'assets/css/dataTables.dataTables.css', array(), time(), false);  
            wp_enqueue_style('jquery-toast-plugin-css', plugin_dir_url(__FILE__) . 'assets/css/jquery.toast.min.css', array(), time(), false);   
                
            wp_enqueue_script('jquery');
            wp_enqueue_script('dataTables-js', plugin_dir_url(__FILE__) . 'assets/js/dataTables.js', array('jquery'), time(), true);   
            wp_enqueue_script('posttitle-js', plugin_dir_url(__FILE__) . 'assets/js/ai_posttitle.js', array('jquery'), time(), true);

            wp_localize_script('posttitle-js', 'ajax_ob', array(
                'ajax_url' => admin_url('admin-ajax.php'),
                'nonce' => wp_create_nonce('ai-seo-content-nonce')
            ));

            wp_enqueue_script('custom-js', plugin_dir_url(__FILE__) . 'assets/js/custom.js', array('jquery'), time(), true);    
            wp_enqueue_script('jquery-toast-plugin', plugin_dir_url(__FILE__) . 'assets/js/jquery.toast.min.js', array('jquery'), time(), true);
          }
        }

        public function otslf_ai_blog_menu()
        {  
            add_menu_page(
                __('Super Fast Blog Ai', 'super-fast-blog-ai'), // Page Title
                __('Super Fast Blog Ai', 'super-fast-blog-ai'), // Menu Title
                'manage_options', // Capability
                'sf-blog-ai', // Page slug
                array($this, 'otslf_ai_blog_dashboard'), // Callback to print HTML
                plugin_dir_url(__FILE__) . 'assets/images/menu_icon.svg'
            );
        }
        

        public function otslf_ai_blog_dashboard(){   

        if (!current_user_can('manage_options')) {
            return;
        }

        $default_tab = 'aiblog';

        $tab = isset($_GET['tab']) ? sanitize_text_field(wp_unslash($_GET['tab'])) : $default_tab;
        // Nonce verification code

        if ( !isset($_GET['tab']) || ! wp_verify_nonce(sanitize_text_field(wp_unslash($_GET['tab'])), 'super-fast-blog-ai') ) {

        echo '<div class="ai-blog-navbar-header">';

        // Here are our tabs

        echo '<nav class="nav-tab-wrapper">';
            echo '<a href="' . esc_url( '?page=sf-blog-ai&tab=aiblog' ) . '"><img src="' . esc_url(OTSLF_AI_BLOG_URL . '/assets/images/logo.svg', __FILE__) .  '" alt="' . esc_attr__('AI Blog', 'super-fast-blog-ai') . '" class="logoimage"></a>';
            echo '<a href="' . esc_url( '?page=sf-blog-ai&tab=aiblog' ) . '" class="nav-tab ' . ( esc_attr( $tab ) === 'aiblog' ? 'nav-tab-active' : '' ) . '"><span class="tab-icon"><svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.628 13.201a.561.561 0 0 0-1.07 0l-.534 1.638-1.636.532a.564.564 0 0 0 0 1.07l1.636.533.535 1.637a.561.561 0 0 0 1.069 0l.534-1.637 1.637-.533a.564.564 0 0 0 0-1.07l-1.637-.532zM1.03 11.406c0 .41.264.776.655.903l4.132 1.343 1.341 4.13a.95.95 0 0 0 1.806 0l1.344-4.13 4.129-1.343a.95.95 0 0 0 0-1.806L10.309 9.16 8.965 5.03a.95.95 0 0 0-1.806 0L5.818 9.16l-4.132 1.343a.95.95 0 0 0-.655.903m7.031-5.515 1.266 3.89a.56.56 0 0 0 .36.36l3.89 1.265-3.89 1.265a.56.56 0 0 0-.36.36l-1.266 3.89-1.266-3.89a.56.56 0 0 0-.36-.36l-3.89-1.265 3.89-1.264a.56.56 0 0 0 .36-.361zm7.284-4.502a.561.561 0 0 0-1.068 0l-.81 2.486-2.487.809a.564.564 0 0 0 0 1.07l2.487.808.81 2.487a.562.562 0 0 0 1.068 0l.81-2.487 2.487-.808a.564.564 0 0 0 0-1.07l-2.487-.809zM3.281 4.656h-.563a.563.563 0 0 0 0 1.125h.563v.563a.563.563 0 0 0 1.125 0V5.78h.562a.563.563 0 0 0 0-1.125h-.562v-.562a.563.563 0 0 0-1.125 0z" fill="url(#a)"/><defs><linearGradient id="a" x1=".65" y1="1" x2="23.043" y2="2.871" gradientUnits="userSpaceOnUse"><stop stop-color="#2F58BA"/><stop offset="1" stop-color="#6F39C4"/></linearGradient></defs></svg></span>' . esc_html__( 'Title Generate', 'super-fast-blog-ai' ) . '</a>';
            echo '<a href="' . esc_url( '?page=sf-blog-ai&tab=ai-article' ) . '" class="nav-tab ' . ( esc_attr( $tab ) === 'ai-article' ? 'nav-tab-active' : '' ) . '"><span class="tab-icon"><svg width="17" height="16" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M14.55.593H1.511a1.48 1.48 0 0 0-1.48 1.481v2.074H8.92l2.014-2.015a1.778 1.778 0 0 1 2.863 2.015h2.234V2.074A1.48 1.48 0 0 0 14.549.593M3.29 2.963a.593.593 0 1 1 0-1.185.593.593 0 0 1 0 1.185m2.37 0a.593.593 0 1 1 0-1.185.593.593 0 0 1 0 1.185m7.704 1.778L9.749 8.33a.9.9 0 0 1-.628.262H7.865a.89.89 0 0 1-.89-.89V6.448a.9.9 0 0 1 .262-.628l1.078-1.078H.031v9.185a1.48 1.48 0 0 0 1.481 1.482H14.55a1.48 1.48 0 0 0 1.482-1.482V4.741zM2.697 7.704h2.37a.296.296 0 0 1 0 .592h-2.37a.296.296 0 0 1 0-.592m0 2.37h8.297a.296.296 0 1 1 0 .593H2.697a.296.296 0 1 1 0-.593m10.667 2.963H2.697a.296.296 0 1 1 0-.593h10.667a.296.296 0 1 1 0 .593m-.35-10.483a1.185 1.185 0 0 1 0 1.677l-3.68 3.68a.3.3 0 0 1-.213.09H7.865a.296.296 0 0 1-.297-.297V6.447a.28.28 0 0 1 .09-.207l3.685-3.686a1.185 1.185 0 0 1 1.671 0" fill="url(#a)"/><defs><linearGradient id="a" x1="16.171" y1="9.481" x2=".031" y2="9.481" gradientUnits="userSpaceOnUse"><stop stop-color="#7E0D9D"/><stop offset=".5" stop-color="#7328F2"/><stop offset="1" stop-color="#51A0F7"/></linearGradient></defs></svg></span>' . esc_html__( 'Article Generate', 'super-fast-blog-ai' ) . '</a>';
            echo '<a href="' . esc_url( '?page=sf-blog-ai&tab=setting' ) . '" class="nav-tab ' . ( esc_attr( $tab ) === 'setting' ? 'nav-tab-active' : '' ) . '"><span class="tab-icon"><svg width="18" height="16" viewBox="0 0 18 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M15.78 5.683c-1.508 0-2.124-1.066-1.374-2.375a1.58 1.58 0 0 0-.584-2.158L12.381.325c-.659-.392-1.509-.158-1.9.5l-.092.158c-.75 1.309-1.983 1.309-2.742 0L7.556.825a1.37 1.37 0 0 0-1.884-.5l-1.441.825a1.59 1.59 0 0 0-.584 2.167c.759 1.3.142 2.366-1.366 2.366-.867 0-1.584.709-1.584 1.584v1.466c0 .867.709 1.584 1.584 1.584 1.508 0 2.125 1.066 1.366 2.375a1.58 1.58 0 0 0 .584 2.158l1.441.825c.659.392 1.509.158 1.9-.5l.092-.158c.75-1.309 1.983-1.309 2.742 0l.091.158c.392.658 1.242.892 1.9.5l1.442-.825a1.58 1.58 0 0 0 .583-2.158c-.758-1.309-.141-2.375 1.367-2.375.867 0 1.583-.709 1.583-1.584V7.267a1.6 1.6 0 0 0-1.591-1.584m-6.75 5.025A2.714 2.714 0 0 1 6.323 8a2.714 2.714 0 0 1 2.709-2.708A2.714 2.714 0 0 1 11.739 8a2.714 2.714 0 0 1-2.708 2.708" fill="url(#a)"/><defs><linearGradient id="a" x1=".345" y1=".134" x2="21.072" y2="1.97" gradientUnits="userSpaceOnUse"><stop stop-color="#2F58BA"/><stop offset="1" stop-color="#6F39C4"/></linearGradient></defs></svg></span>' . esc_html__( 'Setting', 'super-fast-blog-ai' ) . '</a>';
            echo '<a href="' . esc_url( '?page=sf-blog-ai&tab=logschedule' ) . '" class="nav-tab ' . ( esc_attr( $tab ) === 'logschedule' ? 'nav-tab-active' : '' ) . '"><span class="tab-icon"><svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.46 9.643h-1.286v3.428l2.571 1.715.643-1.055-1.929-1.302zm-.43-3L1.03 1.5v6l7.715 1.714-7.714 1.715v6l6.231-2.666a5.996 5.996 0 0 0 5.769 4.38c3.308 0 6-2.692 6-6 0-3.309-2.692-6-6-6m0 10.286a4.287 4.287 0 0 1-4.285-4.26v-.06a4.293 4.293 0 0 1 4.286-4.26 4.287 4.287 0 0 1 4.286 4.285 4.295 4.295 0 0 1-4.286 4.295" fill="url(#a)"/><defs><linearGradient id="a" x1="19.189" y1="11.786" x2="1.031" y2="11.786" gradientUnits="userSpaceOnUse"><stop stop-color="#7E0D9D"/><stop offset=".5" stop-color="#7328F2"/><stop offset="1" stop-color="#51A0F7"/></linearGradient></defs></svg></span>' . esc_html__( 'Log Post', 'super-fast-blog-ai' ) . '</a>';
        echo '</nav>';

        echo '</div>';  
        echo '<div class="tab-content">';
        
        switch ($tab):
            case 'aiblog':
                $this->titlegenerate->otslf_aititel_generate();
            break;
            case 'setting': 
                $this->otslf_ai_settings();
            break;

            case 'ai-article': 
                $this->articlegenerate ->otslf_bloggenerate();
            break;

            case 'logschedule':  
               $this->logschedulepost->otslf_title_log_list();
            break;
        endswitch;
        echo '</div>';

        } else {
            echo 'Nonce verification failed!';
        }  
      }

        public function otslf_ai_settings(){
            $this->setting_instance = new Class_Setting_Management();
            $this->setting_instance->otslf_setting_fields(); 
        }  
    
        public function otslf_initialize_settings() {
            $this->setting_instance = new Class_Setting_Management();
            $this->setting_instance->otslf_settings_init();
        }

        public function otslf_license_activation_page(){
            new Class_Licenseactivation();
        }

    }    
    
    // Initialize the plugin
    new Class_super_fast_blog_ai();
    
    // Include the schedule posts functionality
    include_once(plugin_dir_path(__FILE__) . 'src/Class_Schedule_Posts.php');
    